name: CI

on:
  schedule:
    # Once per day, Monday to Friday
    - cron: '0 19 * * 1-5'
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            make: make
          - os: macos-latest
            make: make
          - os: windows-latest
            make: make
        target:
          - vscode

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6

      # Development testing
      - run: ${{ matrix.platform.make }} webview
      - run: ${{ matrix.platform.make }} ${{ matrix.target }}
      - if: runner.os == 'Linux'
        run: xvfb-run --auto-servernum ${{ matrix.platform.make }} ${{ matrix.target }}-test
      - if: runner.os != 'Linux'
        run: ${{ matrix.platform.make }} ${{ matrix.target }}-test
      - run: ${{ matrix.platform.make }} ${{ matrix.target }}-package

      # Production testing
      - name: Install VSIX extension
        if: runner.os == 'macOS'
        run: >
          ./build/test/vscode/.vscode-test/vscode-*/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code
          --extensions-dir build/test/vscode/.vscode-test/extensions
          --install-extension build/dist/sourcemeta-studio-vscode.vsix
      - name: Install VSIX extension
        if: runner.os == 'Linux'
        run: >
          ./build/test/vscode/.vscode-test/vscode-*/bin/code
          --extensions-dir build/test/vscode/.vscode-test/extensions
          --install-extension build/dist/sourcemeta-studio-vscode.vsix
      - name: Install VSIX extension
        if: runner.os == 'Windows'
        run: |
          $VSCODE_DIR = Get-ChildItem -Path build/test/vscode/.vscode-test -Directory -Filter 'vscode-*' | Select-Object -First 1
          & "$VSCODE_DIR\bin\code.cmd" --extensions-dir build/test/vscode/.vscode-test/extensions --install-extension build/dist/sourcemeta-studio-vscode.vsix
        shell: pwsh

      - if: runner.os == 'Linux'
        run: xvfb-run --auto-servernum ${{ matrix.platform.make }} ${{ matrix.target }}-test
        env:
          VSIX: 1
      - if: runner.os != 'Linux'
        run: ${{ matrix.platform.make }} ${{ matrix.target }}-test
        env:
          VSIX: 1

      - name: Check for uncommitted files
        run: ./scripts/no-uncommitted-files.sh
