name: CI

on:
  schedule:
    # Once per day, Monday to Friday
    - cron: '0 19 * * 1-5'
  push:
    branches:
      - main
  pull_request:

jobs:
  vscode:
    strategy:
      fail-fast: false
      matrix:
        node-version: [ '18.x', '20.x' ]
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: vscode/package-lock.json

      - name: Install extension dependencies
        working-directory: ./vscode
        run: npm ci

      - name: Install webview dependencies
        working-directory: ./webview
        run: npm ci

      - name: Run ESLint
        working-directory: ./vscode
        run: npm run lint

      - name: Compile TypeScript
        working-directory: ./vscode
        run: npm run compile

      - name: Build webview UI
        working-directory: ./vscode
        run: npm run build:webview

      # TODO: Can we unify this difference in a better way?
      - name: Run tests on Linux (with xvfb)
        if: runner.os == 'Linux'
        working-directory: ./vscode
        run: xvfb-run -a npm test
      - name: Run tests on Windows/macOS
        if: runner.os != 'Linux'
        working-directory: ./vscode
        run: npm test

      - name: Check for uncommitted files
        run: ./scripts/no-uncommitted-files.sh
