name: CI

on:
  schedule:
    # Once per day, Monday to Friday
    - cron: '0 19 * * 1-5'
  push:
    branches:
      - main
  pull_request:

jobs:
  vscode:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            make: make
          - os: macos-latest
            make: make
          - os: windows-latest
            make: make
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6

      - run: ${{ matrix.platform.make }} webview

      - name: Install extension dependencies
        working-directory: ./vscode
        run: npm ci
      - name: Run ESLint
        working-directory: ./vscode
        run: npm run lint
      - name: Compile TypeScript
        working-directory: ./vscode
        run: npm run compile

      - if: runner.os == 'Linux'
        run: xvfb-run --auto-servernum ${{ matrix.platform.make }} vscode-test
      - if: runner.os != 'Linux'
        run: ${{ matrix.platform.make }} vscode-test

      - name: Check for uncommitted files
        run: ./scripts/no-uncommitted-files.sh
