name: CI

on:
  schedule:
    # Once per day, Monday to Friday
    - cron: '0 19 * * 1-5'
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            make: make
          - os: macos-latest
            make: make
          - os: windows-latest
            make: make
        target:
          - vscode

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6

      # Development testing
      - run: ${{ matrix.platform.make }} webview
      - run: ${{ matrix.platform.make }} ${{ matrix.target }}
      - if: runner.os == 'Linux'
        run: xvfb-run --auto-servernum ${{ matrix.platform.make }} ${{ matrix.target }}-test
      - if: runner.os != 'Linux'
        run: ${{ matrix.platform.make }} ${{ matrix.target }}-test
      - run: ${{ matrix.platform.make }} ${{ matrix.target }}-package

      # Production testing
      - shell: bash
        run: |
          rm -rf build/test/vscode/.vscode-test/extensions
          mkdir -p build/test/vscode/.vscode-test/extensions/sourcemeta.studio
          unzip build/dist/sourcemeta-studio-vscode.vsix 'extension/*' -d build/test/vscode/.vscode-test/extensions/sourcemeta.studio
          mv build/test/vscode/.vscode-test/extensions/sourcemeta.studio/extension/* build/test/vscode/.vscode-test/extensions/sourcemeta.studio/
          rmdir build/test/vscode/.vscode-test/extensions/sourcemeta.studio/extension
          echo '[{"identifier":{"id":"sourcemeta.studio"},"version":"0.0.1","location":{"$mid":1,"path":"/sourcemeta.studio","scheme":"file"},"relativeLocation":"sourcemeta.studio","metadata":{"isApplicationScoped":false,"isBuiltin":false,"isSystem":false}}]' > build/test/vscode/.vscode-test/extensions/extensions.json
      - if: runner.os == 'Linux'
        run: xvfb-run --auto-servernum ${{ matrix.platform.make }} ${{ matrix.target }}-test
        env:
          VSIX: 1
      - if: runner.os != 'Linux'
        run: ${{ matrix.platform.make }} ${{ matrix.target }}-test
        env:
          VSIX: 1

      - name: Check for uncommitted files
        run: ./scripts/no-uncommitted-files.sh
